### ISSUE TITLE
TCM_006793 does not have domain root specified.

### ISSUE THREAD

**Issue by mycrobe** [warelab/gramene-mongodb#35]
In [v49](http://data.gramene.org/v49/genes?idList=TCM_006793), we see that there's an InterPro domain feature but an empty "domain_root"

In [v50](http://data.gramene.org/v50/genes?idList=TCM_006793), there's an entry but not root.

Is this an issue with the source data?

**Comment by ajo2995** [comment]
The annotation from Interpro is of type "family" only "domain" annotations get combined into a domain architecture and care about the "root" of the domain hierarchy
