### ISSUE TITLE
No simple way to map system_name to species name

### ISSUE THREAD

**Issue by mycrobe** [warelab/gramene-mongodb#41]
There's no endpoint (other than `genes`, which is hardly appropriate) where there's a mapping between `system_name` and `species` (aka `name`). 

You can go `system_name` <=> `taxon_id` in `/maps` and `taxon_id` <=> `species` in `/taxonomy`.

There should be only one request necessary.

To resolve this issue: Add species name to `/maps` and system_name to `taxonomy`.

**Comment by ajo2995** [comment]
You can not get system_name from the taxonomy docs (v50)
