### ISSUE TITLE
Use compara as source for species taxonomy information

### ISSUE THREAD

**Issue by mycrobe** [warelab/gramene-mongodb#42]
Compara databases have a species tree that is consistent with the genomes used to populate the compara instance. Additionally it contains layout information that could simplify the visualization. This layout information is in the same format as in the genetrees themselves, so we have code in  [warelab/gramene-genetree-vis](https://github.com/warelab/gramene-genetree-vis) that [already uses it](https://github.com/warelab/gramene-genetree-vis/blob/master/src/utils/layoutTree.js#L105).

We should either:-
* use this as the source for taxonomy nodes rather than NCBI, or
* use this to decorate NCBI taxonomy nodes with a `subset` property, per #30 

I am leaning toward the former option because it would leave each instance of gramene-swagger with internally consistent datasets.

**Comment by ajo2995** [comment]
For backward compatibility, convert the species tree into the taxonomy collection

**Comment by ajo2995** [comment]
on second thought, lets go with plan B.
Load all NCBI taxonomy nodes into the mongo collection and add an index on the subset property.
Write a script to update the subset property given a set of taxon_ids and a label.
You can use an aggregate query to get the set of ancestors associated with the given taxon_ids. Then update those nodes with the new label.

**Comment by mycrobe** [comment]
I think this is done.
